image: node:18

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &frontend-sonar
        name: sonar frontend
        caches:
          - node
          - sonar
        script:
          - yarn
          - cd packages/web/
          - yarn coverage
          - yarn sonar
    - step: &backend-sonar
        name: sonar backend (sst)
        caches:
          - node
          - sonar
        script:
          - yarn
          - cd packages/functions/
          - yarn coverage
          - yarn sonar
    - step: &dependency-track-backend
        name: Generate and upload BOM file for backend
        script:
          - yarn
          - npm install -g @cyclonedx/bom@3.10.6
          - cyclonedx-node -l -o bom.json
          - 'curl -f -X POST "${DTRACK_URL}/v1/bom" -H "X-Api-Key: ${DTRACK_API_KEY}" -H "Content-Type: multipart/form-data" -F "project=${DTRACK_BACKEND_ID}" -F "bom=@bom.json"'
        artifacts:
          - bom.json
    - step: &dependency-track-frontend
        name: Generate and upload BOM file for frontend
        script:
          - yarn
          - rm -rf packages/web/node_modules && mv node_modules/ packages/web/
          - npm install -g @cyclonedx/bom@3.10.6
          - cd packages/web/
          - cyclonedx-node -l -o bom.json
          - 'curl -f -X POST "${DTRACK_URL}/v1/bom" -H "X-Api-Key: ${DTRACK_API_KEY}" -H "Content-Type: multipart/form-data" -F "project=${DTRACK_FRONTEND_ID}" -F "bom=@bom.json"'
        artifacts:
          - packages/web/bom.json

pipelines:
  pull-requests:
    "**":
      - parallel:
          - step: *backend-sonar
          - step: *frontend-sonar

  branches:
    main:
      - step:
          script:
            - git push --mirror git@github.com:wiiisdom/ec2-leaser.git

  custom:
    dependency-track:
      - parallel:
          - step: *dependency-track-backend
          - step: *dependency-track-frontend
