image: node:18

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
    frontend: frontend/node_module

  steps:
    - step: &frontend-sonar
        name: sonar frontend
        caches:
          - frontend
          - sonar
        script:
          - yarn
          - cd frontend/
          - yarn test:ci
          - yarn sonar
    - step: &backend-sonar
        name: sonar backend (sst)
        caches:
          - node
          - sonar
        script:
          - yarn
          - yarn test
          - yarn sonar
    - step: &dependency-track-backend
        name: Generate and upload BOM file for backend
        script:
          - yarn
          - npm install -g @cyclonedx/bom@3.10.6
          - cyclonedx-node -l -o bom.json
          - 'curl -f -X POST "${DTRACK_URL}/v1/bom" -H "X-Api-Key: ${DTRACK_API_KEY}" -H "Content-Type: multipart/form-data" -F "project=${DTRACK_BACKEND_ID}" -F "bom=@bom.json"'
        artifacts:
          - bom.json
    - step: &dependency-track-frontend
        name: Generate and upload BOM file for frontend
        script:
          - yarn
          - rm -rf frontend/node-modules && mv node-modules/ frontend/
          - npm install -g @cyclonedx/bom@3.10.6
          - cd frontend/
          - cyclonedx-node -l -o bom.json
          - 'curl -f -X POST "${DTRACK_URL}/v1/bom" -H "X-Api-Key: ${DTRACK_API_KEY}" -H "Content-Type: multipart/form-data" -F "project=${DTRACK_FRONTEND_ID}" -F "bom=@bom.json"'
        artifacts:
          - bom.json

pipelines:
  pull-requests:
    "**":
      - parallel:
          - step: *backend-sonar
          - step: *frontend-sonar

  branches:
    main:
      - parallel:
          - step: *backend-sonar
          - step: *frontend-sonar

  custom:
    dependency-track:
      - parallel:
          - step: *dependency-track-backend
          - step: *dependency-track-frontend