image: node:20

clone:
  depth: full

definitions:
  services:
    docker:
      memory: 4096
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store
    sonar: ~/.sonar/cache
  scripts:
    - script:
        &aws curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
        unzip -qq awscliv2.zip;
        ./aws/install;
        export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token;
        echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token
    - script: &pnpm-install corepack enable;
        corepack prepare pnpm@latest-9 --activate;
        pnpm install
  steps:
    - step: &frontend-sonar
        name: sonar frontend
        size: 2x
        caches:
          - pnpm
          - sonar
        script:
          - *pnpm-install
          - cd packages/web/
          - pnpm typecheck
          - pnpm coverage
          - pipe: sonarsource/sonarcloud-scan:3.1.0
            variables:
              EXTRA_ARGS: >
                -Dsonar.organization=${SONAR_ORGANIZATION}
                -Dsonar.projectKey=ec2-leaser-frontend
                -Dsonar.exclusions=src/components/ui/**,src/libs/**
                -Dsonar.sources=src
                -Dsonar.tests=test
                -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
                -Dsonar.testExecutionReportPaths=./sonar-report.xml
              SONAR_SCANNER_OPTS: -Xmx2048m
          - pnpm lint
    - step: &backend-sonar
        name: sonar backend (sst)
        oidc: true
        size: 2x
        caches:
          - pnpm
          - sonar
        script:
          - *aws
          - *pnpm-install
          - pnpm build --stage dev
          - pnpm typecheck
          - cd packages/functions/
          - pnpm typecheck
          - pnpm coverage
          - pipe: sonarsource/sonarcloud-scan:3.1.0
            variables:
              EXTRA_ARGS: >
                -Dsonar.organization=${SONAR_ORGANIZATION}
                -Dsonar.projectKey=ec2-leaser-backend
                -Dsonar.javascript.node.maxspace=4096
                -Dsonar.sources=src
                -Dsonar.tests=test
                -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
                -Dsonar.testExecutionReportPaths=./sonar-report.xml
              SONAR_SCANNER_OPTS: -Xmx4096m
          - pnpm lint

pipelines:
  pull-requests:
    "**":
      - parallel:
          - step: *backend-sonar
          - step: *frontend-sonar

  branches:
    main:
      - parallel:
          - step: *backend-sonar
          - step: *frontend-sonar
      - parallel:
          - step:
              name: Sync to GitHub
              script:
                - git push --mirror git@github.com:wiiisdom/ec2-leaser.git
          - step:
              name: Deploy to production
              caches:
                - pnpm
              oidc: true
              deployment: production
              script:
                - *aws
                - *pnpm-install
                - npx sst deploy --stage prod --region eu-central-1
          - step:
              name: Deploy to demo
              caches:
                - pnpm
              oidc: true
              deployment: demo
              script:
                - *aws
                - *pnpm-install
                - npx sst deploy --stage demo --region us-east-1
