image: node:18

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
    frontend: frontend/node_module

  steps:
    - step: &frontend-sonar
        name: sonar frontend
        caches:
          - frontend
          - sonar
        script:
          - yarn
          - cd frontend/
          - yarn test:ci
          - yarn sonar
    - step: &backend-sonar
        name: sonar backend (sst)
        caches:
          - node
          - sonar
        script:
          - yarn
          - yarn test
          - yarn sonar

pipelines:
  pull-requests:
    "**":
      - parallel:
          - step: *backend-sonar
          - step: *frontend-sonar

  branches:
    main:
      - parallel:
          - step: *backend-sonar
          - step: *frontend-sonar
