image: node:18

clone:
  depth: full

definitions:
  services:
    docker:
      memory: 4096
  caches:
    sonar: ~/.sonar/cache
  scripts:
    - script: &install-trivy apt-get update;
        apt-get install -y wget apt-transport-https gnupg lsb-release;
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | tee /usr/share/keyrings/trivy.gpg > /dev/null;
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | tee -a /etc/apt/sources.list.d/trivy.list;
        apt-get update;
        apt-get install -y trivy;
  steps:
    - step: &frontend-sonar
        name: sonar frontend
        size: 2x
        caches:
          - node
          - sonar
        script:
          - yarn
          - cd packages/web/
          - yarn coverage
          - pipe: sonarsource/sonarcloud-scan:2.0.0
            variables:
              EXTRA_ARGS: >
                -Dsonar.organization=gbandsmith
                -Dsonar.projectKey=ec2-leaser-frontend
                -Dsonar.exclusions=src/components/ui/**,src/libs/**
                -Dsonar.sources=src
                -Dsonar.tests=test
                -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
                -Dsonar.testExecutionReportPaths=./sonar-report.xml
              SONAR_SCANNER_OPTS: -Xmx2048m
          - yarn lint
    - step: &backend-sonar
        name: sonar backend (sst)
        size: 2x
        caches:
          - node
          - sonar
        script:
          - yarn
          - cd packages/functions/
          - yarn coverage
          - pipe: sonarsource/sonarcloud-scan:2.0.0
            variables:
              EXTRA_ARGS: >
                -Dsonar.organization=gbandsmith
                -Dsonar.projectKey=ec2-leaser-backend
                -Dsonar.javascript.node.maxspace=4096
                -Dsonar.sources=src
                -Dsonar.tests=test
                -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
                -Dsonar.testExecutionReportPaths=./sonar-report.xml
              SONAR_SCANNER_OPTS: -Xmx4096m
          - yarn lint

pipelines:
  pull-requests:
    "**":
      - parallel:
          - step: *backend-sonar
          - step: *frontend-sonar

  branches:
    main:
      - parallel:
          - step: *backend-sonar
          - step: *frontend-sonar
      - step:
          script:
            - git push --mirror git@github.com:wiiisdom/ec2-leaser.git

  custom:
    dependency-track:
      - step:
          name: Generate and publish CycloneDX SBOM
          caches:
            - node
          script:
            - *install-trivy
            - yarn install --frozen-lockfile
            - trivy repo --format cyclonedx --output bom.json ./
            - 'curl -f -X POST "${DTRACK_URL}/v1/bom" -H "X-Api-Key: ${DTRACK_API_KEY}" -H "Content-Type: multipart/form-data" -F "project=${DTRACK_PROJECT_ID}" -F "bom=@bom.json"'
          artifacts:
            - bom.json
